"""empty message

Revision ID: afc4045ac807
Revises: 
Create Date: 2019-12-28 22:07:36.301418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc4045ac807'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.String(), nullable=True),
    sa.Column('artist_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id'),
    sa.UniqueConstraint('artist_name'),
    sa.UniqueConstraint('id')
    )
    op.create_table('spotifyuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_user_id', sa.String(), nullable=False),
    sa.Column('spotify_access_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_access_token'),
    sa.UniqueConstraint('spotify_user_id')
    )
    op.create_table('association',
    sa.Column('association_key', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['spotifyuser.id'], ),
    sa.PrimaryKeyConstraint('association_key'),
    sa.UniqueConstraint('association_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('spotifyuser')
    op.drop_table('artist')
    # ### end Alembic commands ###
